Anharmonic potentials in the notebook and julia script (not quite working yet!)
Note quite working yet due to an error in Brooglie:

MethodError: no method matching zero(::Type{Any})